# Generated by Django 5.0 on 2026-05-12 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('isin', models.CharField(blank=True, max_length=12)),
                ('asset_type', models.CharField(choices=[('etf_acc', 'Accumulating ETF'), ('etf_dist', 'Distributing ETF'), ('stock', 'Individual Stock'), ('savings', 'Savings / Cash')], max_length=10)),
                ('units', models.FloatField()),
                ('avg_purchase_price', models.FloatField()),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('current_price', models.FloatField(default=0)),
                ('current_value', models.FloatField(default=0)),
                ('unrealised_gain', models.FloatField(default=0)),
                ('unrealised_gain_pct', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='demo', max_length=100, unique=True)),
                ('savings_total', models.FloatField(default=0)),
                ('emergency_fund_floor', models.FloatField(default=0)),
                ('monthly_investment_budget', models.FloatField(default=0)),
                ('risk_profile', models.CharField(default='balanced', max_length=20)),
                ('tax_bracket', models.FloatField(default=0.42)),
                ('is_married', models.BooleanField(default=False)),
                ('intake_complete', models.BooleanField(default=False)),
                ('strategy_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_at_gain_pct', models.FloatField(default=0.3)),
                ('sell_portion_pct', models.FloatField(default=0.5)),
                ('stop_loss_pct', models.FloatField(default=-0.15)),
                ('stop_loss_action', models.CharField(choices=[('hold', 'Hold'), ('review', 'Review'), ('sell', 'Sell')], default='review', max_length=10)),
                ('sell_before_year_end', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('holding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_rule', to='portfolio.holding')),
            ],
        ),
        migrations.AddField(
            model_name='holding',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.userprofile'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_amount', models.FloatField(default=0)),
                ('target_date', models.CharField(default='open', max_length=20)),
                ('monthly_allocation', models.FloatField(default=0)),
                ('priority', models.IntegerField(default=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='portfolio.userprofile')),
            ],
        ),
    ]
