# Generated by Django 5.0 on 2026-05-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approved_strategy_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_strategy_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='strategy_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
