# Generated by Django 5.0 on 2026-05-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_userprofile_approved_strategy_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='plan_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
