# Generated by Django 5.0 on 2026-06-02 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('chunk_count', models.IntegerField(default=0)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(default=list)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.taxsource')),
            ],
            options={
                'ordering': ['source_id', 'ordinal'],
            },
        ),
    ]
